on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/aearep-2656:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/aearep-2656:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'SvenAelterman/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/aearep-2656:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: aci-aearep-2656
            location: 'east us'
            # Mods
            azure-file-volume-account-key: ${{ secrets.ST_ACCOUNT_KEY }}
            azure-file-volume-account-name: streprodemoeastus01
            azure-file-volume-mount-path: '/mnt/y'
            azure-file-volume-share-name: 'study-repro'
            #command-line: 'cp /mnt/y/aearep-2656/lots-of-research-data.txt /code/results/processed-data.txt'
            command-line: 'touch /mnt/y/aearep-2656/lots-of-research-data-2.txt'
            restart-policy: 'Never'
            
